### ISSUE TITLE
Just use OsmAnd

### ISSUE THREAD

**Issue by nxxxse** [X-Ryl669/BwareArea#3]
Hi, I just saw this app in F-droid and I am curious what the use case is. Having to import a CSV with lat and lon with speedcams is kind of technical and this still leaves the question open who maintains this CSV, is it somehow crowed sourced and so on. Questions over questions. But:

As I see it, the speedcams problem has already been fully solved, and also supporting a fully offline use case which I appreciate by OsmAnd. So I first I thought about different value this app might intend to provide, say stupid example you are restricted to get closer to some random property or whatever as 500 m or so ;-)

What is your take on that?

**Comment by X-Ryl669** [comment]
You guessed right. The speedcam.txt comes from crowd-sourced site (like lufop.net, but since I'm using iGo format, any source should do), but I'm preparing more import source (and probably also directly a database import since CSV is too limited).

OsmAnd is good but it depends on OpenStreetMap which does not cover well my area, and only provide routing for car (not camper/truck unfortunately). In all cases, if you have a navigation application with speedcam warning that suits you, then there is no use for BwareArea.

However, if you have a navigation software that does not provide such feature (like Here wego, Google map, etc...) or use a format you can't source (because it's proprietary, like ov2, ...) or that's too limited (like no traffic cam, no speed section), or because it's illegal in your country (ahem...) then you can use BwareArea "on top".

I've made this tool following a bit the Unix philosophy: it's a simple tool doing a single thing, you can combine with any other tool.

Also, I'm developing an HW based POI warner for my car (based on ESP32 + GPS + Eink screen), so while I was planning the development, I started implementing the algorithms for POI distance measurement and sorting, POI database import and so on, so using Android/Java is a good script language for having some quick code written fast.

**Comment by nxxxse** [comment]
Thanks for the input. Now it all makes more sense to me.
